# render.yaml
services:
  - type: web
    name: roblox-llm-bridge
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: SHARED_SECRET         # [CHANGE]
        sync: false
      - key: OPENAI_API_KEY        # [CHANGE]
        sync: false
      - key: MODEL_NAME
        value: gpt-4o-mini
      - key: SYSTEM_PROMPT         # [CHANGE if needed]
        value: You are a concise Roblox NPC. Answer directly in 1–2 short sentences (9–22 words). No meta talk, no links, no code.
      - key: ATTEMPT_TIMEOUT_SECS
        value: "8.0"
      - key: REQ_TIMEOUT_SECS
        value: "25"
      - key: MAX_RETRIES
        value: "2"
