# server/render.yaml
services:
  - type: web
    name: roblox-chatnpc-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PROVIDER
        value: groq
      - key: MODEL_NAME
        value: llama3-8b-8192
      - key: FAST_REPLY_SECS
        value: "2.6"
      - key: ATTEMPT_TIMEOUT_SECS
        value: "2.2"
      - key: REQ_TIMEOUT_SECS
        value: "45"
      - key: HOST
        value: 0.0.0.0
      # Add GROQ_API_KEY or OPENAI_API_KEY and SHARED_SECRET in the Render dashboard (not in git)
