services:
  - type: web
    name: roblox-ollama-bridge
    runtime: python
    plan: free
    envVars:
      - key: SHARED_SECRET
        sync: false
      - key: OLLAMA_BASE
        value: https://ollamafreeapi.onrender.com
      - key: OLLAMA_ALT_BASE
        value: ""              # optional second base
      - key: OLLAMA_PATH
        value: /chat/completions
      - key: MODEL_NAME
        value: llama3-8b
      - key: TEMP
        value: "0.6"
      - key: MAX_TOKENS
        value: "160"
      - key: ATTEMPT_TIMEOUT_SECS
        value: "6.0"
      - key: REQ_TIMEOUT_SECS
        value: "25"
      - key: MAX_RETRIES
        value: "2"
      - key: RETRY_BACKOFF_SECS
        value: "0.8"
      - key: HOST
        value: 0.0.0.0
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
