services:
  - type: web
    name: roblox-llm7-bridge
    runtime: python
    plan: free
    envVars:
      - key: SHARED_SECRET
        sync: false
      - key: LLM7_BASE
        value: https://llm7.io/v1
      - key: LLM7_API_KEY
        value: unused
      - key: MODEL_NAME
        value: gpt-4
      - key: TEMP
        value: "0.6"
      - key: MAX_TOKENS
        value: "160"
      - key: ATTEMPT_TIMEOUT_SECS
        value: "8.0"
      - key: REQ_TIMEOUT_SECS
        value: "25"
      - key: MAX_RETRIES
        value: "2"
      - key: RETRY_BACKOFF_SECS
        value: "0.8"
      - key: HOST
        value: 0.0.0.0
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
