# render.yaml
services:
  - type: web
    name: roblox-deepseek-bridge
    runtime: python
    plan: free
    envVars:
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: MODEL_NAME
        value: deepseek-chat
      - key: SHARED_SECRET
        sync: false
      - key: ATTEMPT_TIMEOUT_SECS
        value: "4.0"
      - key: REQ_TIMEOUT_SECS
        value: "30"
      - key: HOST
        value: 0.0.0.0
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
